add app name to fly deploy command to fix error
Error: the config for your app is missing an app name, add an app field to the fly.toml file or specify with the -a flag`

https://community.fly.io/t/upgraded-fly-cli-version-error-the-config-for-your-app-is-missing-an-app-name/13002